### PR TITLE
Update tray.ts to app.exit() instead of app.quit()

### PR DESCRIPTION
**Pull request by hanwin**

### CODE REVIEW

**Comment by hanwin** [comment]
Bare with me I am new to using Git and pull requests :)

**Comment by josephdadams** [comment]
`app.exit()` will force quit. Which will cause things like this to not run:

https://github.com/josephdadams/screendeck/blob/a79099fecb15832c87e1fab5bc54aefb094d2afe/src/main.ts#L28

Is the app not closing for you?

**Comment by hanwin** [comment]
Yes, when I click on "quit" in the stak bar the app does not quit

**Comment by josephdadams** [comment]
Let’s debug that then first if you don’t mind. Maybe it is the Hotkey thing in the `will-quit` event. 

What OS are you on? I think I am experiencing this on MacOS.

**Comment by hanwin** [comment]
Ofcource. "quit" may not be the best solution.
For the record so File->exit does not work either

**Comment by hanwin** [comment]
I realise that it's not a bug it's a feature, maybe.
You just quit (or hide) the form with buttons. You dont't quit the application, right?

**Comment by josephdadams** [comment]
No it’s a bug. It’s definitely supposed to be able to quit properly.

**Comment by davidjoshuaford** [comment]
I'm getting the same - running arm64 version on Macbook Pro M1 Max and it won't quit without force quitting. Also tried the Intel version with the same result.

**Comment by josephdadams** [comment]
I’ll be releasing a bugfix version soon as I’m pretty sure I’ve found the problem

**Comment by josephdadams** [comment]
@hanwin thank you again for this PR. I will not be merging it due to the way I implemented the fix in https://github.com/josephdadams/screendeck/commit/a2eb04b7693b74b2c1ec93648a288e61a1a1a305

However please don't let this deter you from future commits to the project as I do desire for this to be a community contributed program. Thank you!

**Pull request closed without merging**
